# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uhd_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(859, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.save_path_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.save_path_edit.setObjectName("save_path_edit")
        self.horizontalLayout_2.addWidget(self.save_path_edit)
        self.save_path_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_path_btn.setObjectName("save_path_btn")
        self.horizontalLayout_2.addWidget(self.save_path_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.fc_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.fc_spinBox.setMinimumSize(QtCore.QSize(200, 0))
        self.fc_spinBox.setMaximum(600000000)
        self.fc_spinBox.setProperty("value", 100)
        self.fc_spinBox.setObjectName("fc_spinBox")
        self.horizontalLayout_3.addWidget(self.fc_spinBox)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.bw_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.bw_spinBox.setMinimumSize(QtCore.QSize(200, 0))
        self.bw_spinBox.setProperty("value", 20)
        self.bw_spinBox.setObjectName("bw_spinBox")
        self.horizontalLayout_4.addWidget(self.bw_spinBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.sample_nums_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sample_nums_doubleSpinBox.setMinimumSize(QtCore.QSize(200, 0))
        self.sample_nums_doubleSpinBox.setDecimals(0)
        self.sample_nums_doubleSpinBox.setMaximum(100000000000.0)
        self.sample_nums_doubleSpinBox.setSingleStep(10000.0)
        self.sample_nums_doubleSpinBox.setProperty("value", 10000000.0)
        self.sample_nums_doubleSpinBox.setObjectName("sample_nums_doubleSpinBox")
        self.horizontalLayout_5.addWidget(self.sample_nums_doubleSpinBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.ok_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ok_btn.setMinimumSize(QtCore.QSize(150, 50))
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout.addWidget(self.ok_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.plot_btn = QtWidgets.QPushButton(self.centralwidget)
        self.plot_btn.setObjectName("plot_btn")
        self.horizontalLayout.addWidget(self.plot_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "文件保存路径:"))
        self.save_path_btn.setText(_translate("MainWindow", "选择"))
        self.label_3.setText(_translate("MainWindow", "中心频率:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "MHz"))
        self.comboBox.setItemText(1, _translate("MainWindow", "KHz"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Hz"))
        self.label_4.setText(_translate("MainWindow", "采样带宽:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "MHz"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "KHz"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Hz"))
        self.label_5.setText(_translate("MainWindow", "样点个数:"))
        self.ok_btn.setText(_translate("MainWindow", "确认"))
        self.plot_btn.setText(_translate("MainWindow", "绘图"))

